### ISSUE TITLE
Deprecation warning with Webpack 4.x

### ISSUE THREAD

**Issue by joffotron** [mgcrea/webpack-component-resolver-plugin#1]
Hi!

We've updated to Webpack 4.x and are using this resolver plugin. However now we are seeing deprecation warnings related to it:

```sh
$ node --trace-deprecation ./node_modules/.bin/webpack --progress --color --mode development
 10% building modules 1/1 modules 0 active(node:28) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ComponentResolverPlugin.apply (/app/node_modules/component-webpack-resolver-plugin/src/index.js:11:14)
    at plugins.forEach.plugin (/app/node_modules/enhanced-resolve/lib/ResolverFactory.js:276:10)
```

Is this a quick fix, or is there another resolver plugin you could recommend?

Thanks

Edit: The full error output is here: https://gist.github.com/joffotron/b517f64df99b6a790043e9bfe6df4814

It seems there are a couple of places that might be affected

**Comment by mgcrea** [comment]
This plugin is deprecated and the recommended usage is directly via a babel plugin:

- https://github.com/mgcrea/babel-plugin-component-resolver

I'll update the README.
